/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wanghong_webpnative_WebPNative */

#ifndef _Included_com_wanghong_webpnative_WebPNative
#define _Included_com_wanghong_webpnative_WebPNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wanghong_webpnative_WebPNative
 * Method:    checkWebPVersion
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wanghong_webpnative_WebPNative_checkWebPVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_wanghong_webpnative_WebPNative
 * Method:    initialize
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_wanghong_webpnative_WebPNative_initialize
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_wanghong_webpnative_WebPNative
 * Method:    hasNextFrame
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wanghong_webpnative_WebPNative_hasNextFrame
  (JNIEnv *, jobject);

/*
 * Class:     com_wanghong_webpnative_WebPNative
 * Method:    nextFrame
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_wanghong_webpnative_WebPNative_nextFrame
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
